# SwiftLint Configuration for WeDaApp
# For all available rules, see: https://realm.github.io/SwiftLint/rule-directory.html

# Paths to exclude from linting
excluded:
  - Pods
  - ArkanaKeys
  - .build
  - "**/.build"
  - DerivedData
  - fastlane
  - vendor
  - "**/Generated"
  - "**/*.generated.swift"

# Paths to include for linting (if you want to be explicit)
included:
  - WeDaApp
  - NetworkingKit
  - DollarGeneralPersist
  - DollarGeneralTemplateHelpers

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments
  - line_length # Can be too restrictive for SwiftUI
  - force_try # Allow force try in tests
  - force_cast # Allow force cast in tests
  - file_header # Disable file header enforcement globally
  - implicitly_unwrapped_optional # Common pattern in XCTest
  - force_unwrapping # Allow in tests and where necessary
  - function_body_length # Allow longer functions in BDD tests
  - static_over_final_class # Allow class methods in test specs

# Rule customization
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 400  # Allow longer test classes
  error: 600

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i  # Common loop variable
    - h  # Color components
    - r  # Red color component
    - g  # Green color component
    - b  # Blue color component
    - a  # Alpha color component
    - dt
    - LogInfo  # Public logging functions follow Swift's print() convention
    - LogError
    - LogDebug

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Vertical whitespace in tests is acceptable for readability
vertical_whitespace_opening_braces:
  severity: warning

# Custom reporter
reporter: "xcode"
